ci:
  autofix_commit_msg: |
    Apply automatic fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: 'ci: Bump pre-commit hooks'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff # Runs ruff linter (replaces flake8)
        args: [--fix, --exit-non-zero-on-fix] # --fix for fixing errors
      - id: ruff-format
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.2
    hooks:
      - id: sphinx-lint
        name: Lint RST files in docs folder using Sphinx Lint
        files: ^((docs/en)/.*\.(rst|inc))|CONTRIBUTING.rst$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: ['types-PyYAML<=6.0.12.12']
        # ignore wrapper scripts because of name colision with efuse/__init__.py etc.
        exclude: test/|docs/|espefuse.py|espsecure.py|esptool.py|esp_rfc2217_server.py
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.11.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --allow-breaking

default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]
