repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff # Runs ruff linter (replaces flake8)
        args: [--fix, --exit-non-zero-on-fix] # --fix for fixing errors
      - id: ruff-format
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.6.8
    hooks:
      - id: sphinx-lint
        name: Lint RST files in docs folder using Sphinx Lint
        files: ^((docs/en)/.*\.(rst|inc))|CONTRIBUTING.rst$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1  # the last version running on py3.7
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        # ignore wrapper scripts because of name colision with efuse/__init__.py etc.
        exclude: test/|docs/|espefuse.py|espsecure.py|esptool.py
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
    - id: codespell
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.4.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg]
