# This workflow will upload an esptool Python package when a dev release tag (e.g. "v4.7.dev2") is pushed

name: PyPI dev release

on:
  push:
    tags:
      - v*.*.dev*

jobs:
  build_and_upload:

    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref_name, 'dev')

    environment:
      name: pypi
      url: https://pypi.org/p/esptool

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.14
      uses: actions/setup-python@master
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build

    - name: Create development release ${{ github.ref_name }}
      run: |
        python ci/patch_dev_release.py --version ${{ github.ref_name }} esptool/__init__.py
        git diff
        echo "Packaging esptool development release: ${{ github.ref_name }}"
        python -m build --sdist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
